# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: meteor.js CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
   # branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    #strategy:
     # matrix:
       # node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Git Clone 
      - uses: actions/checkout@v3
      #- name: Use Node.js ${{ matrix.node-version }}
        #uses: actions/setup-node@v3
        #with:
          #node-version: ${{ matrix.node-version }}
          #cache: 'npm'
      
      #- run: npm ci
      - name: Meteor Install
        shell: bash -l {0}
        run: | 
          curl https://install.meteor.com/?release\=3.00 | sh

      - name: NPM Install
        shell: bash -l {0}
        run: | 
          meteor npm install

      #- name: Create SSH Files
       # shell: bash -l {0}
        #run : | mkdir .delploy
         #      echo "$STAGING_SETTTINGS_JSON > .deploy/settings.json
        #env:
         # STAGING_SETTINGS_JSON: ${{ secrets.STAGING_SETTINGS_JSON}}
          
      - run: npm run build --if-present
      - run: npm test
